
export const COMPANY_INFO = {
  name: 'Carryint Shipping Services L.L.C',
  address: 'Mo2, Al Khabeesi Building, 20th St, Al Khabaisi, Deira, Dubai, UAE',
  contact: '+971 563034626',
  email: 'info@carryint.com',
  website: 'www.carryint.com',
  bank: {
    name: 'Carryint Shipping Services LLC',
    cif: '016098528',
    accNo: '019102017222',
    iban: 'AE970330000019102017222'
  },
  // Updated with a high-quality logo URL matching the provided image
  logoUrl: 'https://i.ibb.co/LhyM4pL/Carryint-Logo.png'
};

export const COUNTRY_CODES = [
  { code: '+971', name: 'UAE' },
  { code: '+91', name: 'India' },
  { code: '+1', name: 'USA' },
  { code: '+44', name: 'UK' },
  { code: '+966', name: 'Saudi Arabia' },
  { code: '+968', name: 'Oman' },
  { code: '+974', name: 'Qatar' },
  { code: '+965', name: 'Kuwait' },
  { code: '+973', name: 'Bahrain' },
  { code: '+886', name: 'Taiwan' },
  { code: '+852', name: 'Hong Kong' },
  { code: '+853', name: 'Macau' }
];

export const ALL_COUNTRIES = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Indian Ocean Territory',
  'British Virgin Islands',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Caribbean Netherlands',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Christmas Island',
  'Cocos (Keeling) Islands',
  'Colombia',
  'Comoros',
  'Cook Islands',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Curaçao',
  'Cyprus',
  'Czechia',
  'DR Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Falkland Islands',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern and Antarctic Lands',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard Island and McDonald Islands',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Ivory Coast',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macau',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'North Korea',
  'North Macedonia',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn Islands',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Republic of the Congo',
  'Romania',
  'Russia',
  'Rwanda',
  'Réunion',
  'Saint Barthélemy',
  'Saint Helena, Ascension and Tristan da Cunha',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Martin',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen',
  'Sweden',
  'Switzerland',
  'Syria',
  'São Tomé and Príncipe',
  'Taiwan',
  'Taiwan (Republic of China)',
  'Chinese Taipei',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'United States Minor Outlying Islands',
  'United States Virgin Islands',
  'United States of America',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Wallis and Futuna',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe',
  'Åland Islands'
];

export const COUNTRY_SHORT_NAMES: Record<string, string> = {
  'Afghanistan': 'AFG',
  'Albania': 'ALB',
  'Algeria': 'DZA',
  'American Samoa': 'ASM',
  'Andorra': 'AND',
  'Angola': 'AGO',
  'Anguilla': 'AIA',
  'Antarctica': 'ATA',
  'Antigua and Barbuda': 'ATG',
  'Argentina': 'ARG',
  'Armenia': 'ARM',
  'Aruba': 'ABW',
  'Australia': 'AUS',
  'Austria': 'AUT',
  'Azerbaijan': 'AZE',
  'Bahamas': 'BHS',
  'Bahrain': 'BHR',
  'Bangladesh': 'BGD',
  'Barbados': 'BRB',
  'Belarus': 'BLR',
  'Belgium': 'BEL',
  'Belize': 'BLZ',
  'Benin': 'BEN',
  'Bermuda': 'BMU',
  'Bhutan': 'BTN',
  'Bolivia': 'BOL',
  'Bosnia and Herzegovina': 'BIH',
  'Botswana': 'BWA',
  'Bouvet Island': 'BVT',
  'Brazil': 'BRA',
  'British Indian Ocean Territory': 'IOT',
  'British Virgin Islands': 'VGB',
  'Brunei': 'BRN',
  'Bulgaria': 'BGR',
  'Burkina Faso': 'BFA',
  'Burundi': 'BDI',
  'Cambodia': 'KHM',
  'Cameroon': 'CMR',
  'Canada': 'CAN',
  'Cape Verde': 'CPV',
  'Caribbean Netherlands': 'BES',
  'Cayman Islands': 'CYM',
  'Central African Republic': 'CAF',
  'Chad': 'TCD',
  'Chile': 'CHL',
  'China': 'CHN',
  'Christmas Island': 'CXR',
  'Cocos (Keeling) Islands': 'CCK',
  'Colombia': 'COL',
  'Comoros': 'COM',
  'Cook Islands': 'COK',
  'Costa Rica': 'CRI',
  'Croatia': 'HRV',
  'Cuba': 'CUB',
  'Curaçao': 'CUW',
  'Cyprus': 'CYP',
  'Czechia': 'CZE',
  'DR Congo': 'COD',
  'Denmark': 'DNK',
  'Djibouti': 'DJI',
  'Dominica': 'DMA',
  'Dominican Republic': 'DOM',
  'Ecuador': 'ECU',
  'Egypt': 'EGY',
  'El Salvador': 'SLV',
  'Equatorial Guinea': 'GNQ',
  'Eritrea': 'ERI',
  'Estonia': 'EST',
  'Eswatini': 'SWZ',
  'Ethiopia': 'ETH',
  'Falkland Islands': 'FLK',
  'Faroe Islands': 'FRO',
  'Fiji': 'FJI',
  'Finland': 'FIN',
  'France': 'FRA',
  'French Guiana': 'GUF',
  'French Polynesia': 'PYF',
  'French Southern and Antarctic Lands': 'ATF',
  'Gabon': 'GAB',
  'Gambia': 'GMB',
  'Georgia': 'GEO',
  'Germany': 'DEU',
  'Ghana': 'GHA',
  'Gibraltar': 'GIB',
  'Greece': 'GRC',
  'Greenland': 'GRL',
  'Grenada': 'GRD',
  'Guadeloupe': 'GLP',
  'Guam': 'GUM',
  'Guatemala': 'GTM',
  'Guernsey': 'GGY',
  'Guinea': 'GIN',
  'Guinea-Bissau': 'GNB',
  'Guyana': 'GUY',
  'Haiti': 'HTI',
  'Heard Island and McDonald Islands': 'HMD',
  'Honduras': 'HND',
  'Hong Kong': 'HKG',
  'Hungary': 'HUN',
  'Iceland': 'ISL',
  'India': 'IND',
  'Indonesia': 'IDN',
  'Iran': 'IRN',
  'Iraq': 'IRQ',
  'Ireland': 'IRL',
  'Isle of Man': 'IMN',
  'Israel': 'ISR',
  'Italy': 'ITA',
  'Ivory Coast': 'CIV',
  'Jamaica': 'JAM',
  'Japan': 'JPN',
  'Jersey': 'JEY',
  'Jordan': 'JOR',
  'Kazakhstan': 'KAZ',
  'Kenya': 'KEN',
  'Kiribati': 'KIR',
  'Kosovo': 'UNK',
  'Kuwait': 'KWT',
  'Kyrgyzstan': 'KGZ',
  'Laos': 'LAO',
  'Latvia': 'LVA',
  'Lebanon': 'LBN',
  'Lesotho': 'LSO',
  'Liberia': 'LBR',
  'Libya': 'LBY',
  'Liechtenstein': 'LIE',
  'Lithuania': 'LTU',
  'Luxembourg': 'LUX',
  'Macau': 'MAC',
  'Madagascar': 'MDG',
  'Malawi': 'MWI',
  'Malaysia': 'MYS',
  'Maldives': 'MDV',
  'Mali': 'MLI',
  'Malta': 'MLT',
  'Marshall Islands': 'MHL',
  'Martinique': 'MTQ',
  'Mauritania': 'MRT',
  'Mauritius': 'MUS',
  'Mayotte': 'MYT',
  'Mexico': 'MEX',
  'Micronesia': 'FSM',
  'Moldova': 'MDA',
  'Monaco': 'MCO',
  'Mongolia': 'MNG',
  'Montenegro': 'MNE',
  'Montserrat': 'MSR',
  'Morocco': 'MAR',
  'Mozambique': 'MOZ',
  'Myanmar': 'MMR',
  'Namibia': 'NAM',
  'Nauru': 'NRU',
  'Nepal': 'NPL',
  'Netherlands': 'NLD',
  'New Caledonia': 'NCL',
  'New Zealand': 'NZL',
  'Nicaragua': 'NIC',
  'Niger': 'NER',
  'Nigeria': 'NGA',
  'Niue': 'NIU',
  'Norfolk Island': 'NFK',
  'North Korea': 'PRK',
  'North Macedonia': 'MKD',
  'Northern Mariana Islands': 'MNP',
  'Norway': 'NOR',
  'Oman': 'OMN',
  'Pakistan': 'PAK',
  'Palau': 'PLW',
  'Palestine': 'PSE',
  'Panama': 'PAN',
  'Papua New Guinea': 'PNG',
  'Paraguay': 'PRY',
  'Peru': 'PER',
  'Philippines': 'PHL',
  'Pitcairn Islands': 'PCN',
  'Poland': 'POL',
  'Portugal': 'PRT',
  'Puerto Rico': 'PRI',
  'Qatar': 'QAT',
  'Republic of the Congo': 'COG',
  'Romania': 'ROU',
  'Russia': 'RUS',
  'Rwanda': 'RWA',
  'Réunion': 'REU',
  'Saint Barthélemy': 'BLM',
  'Saint Helena, Ascension and Tristan da Cunha': 'SHN',
  'Saint Kitts and Nevis': 'KNA',
  'Saint Lucia': 'LCA',
  'Saint Martin': 'MAF',
  'Saint Pierre and Miquelon': 'SPM',
  'Saint Vincent and the Grenadines': 'VCT',
  'Samoa': 'WSM',
  'San Marino': 'SMR',
  'Saudi Arabia': 'SAU',
  'Senegal': 'SEN',
  'Serbia': 'SRB',
  'Seychelles': 'SYC',
  'Sierra Leone': 'SLE',
  'Singapore': 'SGP',
  'Sint Maarten': 'SXM',
  'Slovakia': 'SVK',
  'Slovenia': 'SVN',
  'Solomon Islands': 'SLB',
  'Somalia': 'SOM',
  'South Africa': 'ZAF',
  'South Georgia': 'SGS',
  'South Korea': 'KOR',
  'South Sudan': 'SSD',
  'Spain': 'ESP',
  'Sri Lanka': 'LKA',
  'Sudan': 'SDN',
  'Suriname': 'SUR',
  'Svalbard and Jan Mayen': 'SJM',
  'Sweden': 'SWE',
  'Switzerland': 'CHE',
  'Syria': 'SYR',
  'São Tomé and Príncipe': 'STP',
  'Taiwan': 'TWN',
  'Taiwan (Republic of China)': 'TWN',
  'Chinese Taipei': 'TWN',
  'Tajikistan': 'TJK',
  'Tanzania': 'TZA',
  'Thailand': 'THA',
  'Timor-Leste': 'TLS',
  'Togo': 'TGO',
  'Tokelau': 'TKL',
  'Tonga': 'TON',
  'Trinidad and Tobago': 'TTO',
  'Tunisia': 'TUN',
  'Turkey': 'TUR',
  'Turkmenistan': 'TKM',
  'Turks and Caicos Islands': 'TCA',
  'Tuvalu': 'TUV',
  'Uganda': 'UGA',
  'Ukraine': 'UKR',
  'United Arab Emirates': 'UAE',
  'United Kingdom': 'UK',
  'United States': 'USA',
  'United States Minor Outlying Islands': 'UMI',
  'United States Virgin Islands': 'VIR',
  'United States of America': 'USA',
  'Uruguay': 'URY',
  'Uzbekistan': 'UZB',
  'Vanuatu': 'VUT',
  'Vatican City': 'VAT',
  'Venezuela': 'VEN',
  'Vietnam': 'VNM',
  'Wallis and Futuna': 'WLF',
  'Western Sahara': 'ESH',
  'Yemen': 'YEM',
  'Zambia': 'ZMB',
  'Zimbabwe': 'ZWE',
  'Åland Islands': 'ALA'
};

export const DESTINATION_COUNTRIES = ALL_COUNTRIES;

export const COMMODITY_TYPES = [
  'General Cargo', 'Commercial', 'Electronics', 'Textiles', 'Perishables', 'Auto Parts', 'Hazardous', 'Personal Effects', 'Documents', 'Sample'
];
